// ═══════════════════════════════════════════════════════
// OPS PACK — Incident management, vendor onboarding,
// inventory alerts, SLA monitoring
// ═══════════════════════════════════════════════════════

import type { WorkflowPack } from "./index";

export const opsPack: WorkflowPack = {
  id: "ops",
  name: "Ops Pack",
  description: "Automate incident management, vendor onboarding, inventory monitoring, and SLA tracking",
  icon: "⚙️",
  color: "#14B8A6",
  requiredIntegrations: ["slack", "gmail", "google_sheets"],
  workflows: [
    // ── 1. Incident Escalation ──────────────────────────
    {
      id: "ops-incident-escalation",
      name: "Incident Escalation",
      description: "Receives incident alerts, classifies severity, pages on-call, coordinates response, runs post-mortem",
      triggerEvent: "incident.triggered",
      tags: ["incident", "escalation", "on-call"],
      estimatedCostCents: 5,
      nodes: [
        {
          id: "classify_incident",
          name: "Classify Incident",
          type: "ai_classify",
          config: {
            text: "{{trigger.payload.description}}",
            categories: ["sev1_outage", "sev2_degraded", "sev3_minor", "sev4_cosmetic"],
            context: { service: "{{trigger.payload.service}}", source: "{{trigger.source}}", metrics: "{{trigger.payload.metrics}}" },
            model: "haiku",
          },
        },
        {
          id: "generate_impact",
          name: "Assess Impact",
          type: "ai_generate",
          config: {
            instructions: "Assess the blast radius and customer impact of this incident. Identify affected services, estimated users impacted, revenue risk, and recommended immediate actions. Return JSON with: affectedServices, estimatedUsersImpacted, revenueRisk (low/medium/high/critical), immediateActions (array).",
            context: { description: "{{trigger.payload.description}}", severity: "{{classify_incident.category}}", service: "{{trigger.payload.service}}" },
            model: "sonnet",
          },
          dependsOn: ["classify_incident"],
        },
        {
          id: "route_severity",
          name: "Route by Severity",
          type: "condition",
          config: { category: "{{classify_incident.category}}" },
          dependsOn: ["classify_incident"],
        },
        {
          id: "page_oncall",
          name: "Page On-Call Engineer",
          type: "action",
          config: { action: "send_slack", channel: "#incidents", message: "🔴 SEV1/SEV2 INCIDENT: {{trigger.payload.service}}\n{{trigger.payload.description}}\n\nImpact: {{generate_impact.output.estimatedUsersImpacted}} users affected\nImmediate actions: {{generate_impact.output.immediateActions}}" },
          dependsOn: ["route_severity", "generate_impact"],
        },
        {
          id: "create_channel",
          name: "Create Incident Channel",
          type: "action",
          config: { action: "create_task", title: "Create Slack channel #inc-{{trigger.payload.incidentId}} and invite responders", priority: "critical" },
          dependsOn: ["route_severity"],
        },
        {
          id: "log_minor",
          name: "Log Minor Incident",
          type: "action",
          config: { action: "send_slack", channel: "#ops-log", message: "⚠️ Minor incident logged: {{trigger.payload.service}} — {{trigger.payload.description}}" },
          dependsOn: ["route_severity"],
        },
        {
          id: "notify_stakeholders",
          name: "Notify Stakeholders",
          type: "ai_generate",
          config: {
            instructions: "Write a brief, clear incident notification email for non-technical stakeholders (execs, customer success). State what happened, what's affected, what we're doing about it, and expected resolution time. No jargon. Under 100 words.",
            context: { description: "{{trigger.payload.description}}", severity: "{{classify_incident.category}}", impact: "{{generate_impact.output}}" },
            model: "haiku",
          },
          dependsOn: ["generate_impact"],
        },
        {
          id: "send_stakeholder_email",
          name: "Send Stakeholder Email",
          type: "action",
          config: { action: "send_email", to: "{{trigger.payload.stakeholderEmail}}", subject: "[{{classify_incident.category}}] Incident: {{trigger.payload.service}}", body: "{{notify_stakeholders.rawText}}" },
          dependsOn: ["notify_stakeholders"],
        },
      ],
      edges: [
        { from: "classify_incident", to: "generate_impact" },
        { from: "classify_incident", to: "route_severity" },
        { from: "route_severity", to: "page_oncall", condition: { field: "category", operator: "contains", value: "sev1" } },
        { from: "route_severity", to: "page_oncall", condition: { field: "category", operator: "contains", value: "sev2" } },
        { from: "route_severity", to: "create_channel", condition: { field: "category", operator: "contains", value: "sev1" } },
        { from: "route_severity", to: "log_minor", condition: { field: "category", operator: "contains", value: "sev3" } },
        { from: "route_severity", to: "log_minor", condition: { field: "category", operator: "contains", value: "sev4" } },
        { from: "generate_impact", to: "page_oncall" },
        { from: "generate_impact", to: "notify_stakeholders" },
        { from: "notify_stakeholders", to: "send_stakeholder_email" },
      ],
    },

    // ── 2. Vendor Onboarding ────────────────────────────
    {
      id: "ops-vendor-onboarding",
      name: "Vendor Onboarding",
      description: "Collects vendor info, runs compliance checks, creates accounts, routes for approval",
      triggerEvent: "vendor.submitted",
      tags: ["vendor", "onboarding", "compliance"],
      estimatedCostCents: 6,
      nodes: [
        {
          id: "extract_vendor_info",
          name: "Extract Vendor Details",
          type: "ai_extract",
          config: {
            text: "{{trigger.payload.application}}",
            fields: [
              { name: "companyName", type: "string", description: "Vendor company name" },
              { name: "contactName", type: "string", description: "Primary contact person" },
              { name: "contactEmail", type: "string", description: "Contact email address" },
              { name: "services", type: "array", description: "Services the vendor provides" },
              { name: "annualValue", type: "number", description: "Estimated annual contract value" },
              { name: "certifications", type: "array", description: "Compliance certifications (SOC2, ISO, etc.)" },
              { name: "insuranceCoverage", type: "string", description: "Insurance type and coverage amount" },
            ],
            model: "haiku",
          },
        },
        {
          id: "compliance_check",
          name: "AI Compliance Assessment",
          type: "ai_decide",
          config: {
            question: "Does this vendor meet our compliance and risk requirements?",
            options: ["approved", "needs_review", "requires_additional_docs", "rejected"],
            context: { vendor: "{{extract_vendor_info.extracted}}", requirements: "SOC2 or ISO 27001 required for data-handling vendors. Insurance minimum $1M. No sanctioned entities." },
            criteria: "Check certifications against requirements, verify insurance minimums, flag any missing documentation.",
            model: "sonnet",
          },
          dependsOn: ["extract_vendor_info"],
        },
        {
          id: "route_compliance",
          name: "Route by Compliance",
          type: "condition",
          config: { decision: "{{compliance_check.decision}}" },
          dependsOn: ["compliance_check"],
        },
        {
          id: "request_approval",
          name: "Request Procurement Approval",
          type: "approval",
          config: {
            title: "Vendor Onboarding: {{extract_vendor_info.extracted.companyName}} — {{extract_vendor_info.extracted.annualValue}}/yr",
            description: "Services: {{extract_vendor_info.extracted.services}}\nCertifications: {{extract_vendor_info.extracted.certifications}}\nCompliance: {{compliance_check.decision}} — {{compliance_check.reasoning}}",
            channels: ["slack", "email", "dashboard"],
            priority: "medium",
            expiresInMinutes: 4320,
          },
          dependsOn: ["route_compliance"],
        },
        {
          id: "request_docs",
          name: "Request Additional Documents",
          type: "ai_generate",
          config: {
            instructions: "Write a professional email requesting the specific missing documents or certifications needed. Be clear about what's needed and why. Include a deadline of 2 weeks. Under 150 words.",
            context: { vendor: "{{extract_vendor_info.extracted}}", assessment: "{{compliance_check}}" },
            model: "haiku",
          },
          dependsOn: ["route_compliance"],
        },
        {
          id: "send_docs_request",
          name: "Send Docs Request Email",
          type: "action",
          config: { action: "send_email", to: "{{extract_vendor_info.extracted.contactEmail}}", subject: "Additional documentation needed — {{extract_vendor_info.extracted.companyName}}", body: "{{request_docs.rawText}}" },
          dependsOn: ["request_docs"],
        },
        {
          id: "setup_vendor",
          name: "Create Vendor Record",
          type: "action",
          config: { action: "create_task", title: "Set up vendor account: {{extract_vendor_info.extracted.companyName}}", description: "Create vendor record, assign vendor ID, set up payment terms", priority: "medium" },
          dependsOn: ["request_approval"],
        },
        {
          id: "notify_ops",
          name: "Notify Ops Team",
          type: "action",
          config: { action: "send_slack", channel: "#ops", message: "New vendor onboarding: {{extract_vendor_info.extracted.companyName}} — {{compliance_check.decision}}" },
          dependsOn: ["compliance_check"],
        },
      ],
      edges: [
        { from: "extract_vendor_info", to: "compliance_check" },
        { from: "compliance_check", to: "route_compliance" },
        { from: "compliance_check", to: "notify_ops" },
        { from: "route_compliance", to: "request_approval", condition: { field: "decision", operator: "eq", value: "approved" } },
        { from: "route_compliance", to: "request_approval", condition: { field: "decision", operator: "eq", value: "needs_review" } },
        { from: "route_compliance", to: "request_docs", condition: { field: "decision", operator: "eq", value: "requires_additional_docs" } },
        { from: "request_docs", to: "send_docs_request" },
        { from: "request_approval", to: "setup_vendor" },
      ],
    },

    // ── 3. Inventory Alerts ─────────────────────────────
    {
      id: "ops-inventory-alerts",
      name: "Inventory Monitoring",
      description: "Monitors stock levels, predicts shortages, triggers reorder workflows, alerts team",
      triggerEvent: "inventory.low_stock",
      triggerSchedule: "0 8 * * *",
      tags: ["inventory", "alerts", "reorder"],
      estimatedCostCents: 4,
      nodes: [
        {
          id: "fetch_inventory",
          name: "Fetch Inventory Levels",
          type: "fetch",
          config: { provider: "internal", operation: "inventory.low_stock", params: {} },
        },
        {
          id: "analyze_inventory",
          name: "AI Analyze Stock Levels",
          type: "ai_decide",
          config: {
            question: "Which items need reordering and what priority?",
            options: ["urgent_reorder", "reorder_soon", "monitor", "overstock_alert"],
            context: { inventory: "{{fetch_inventory}}" },
            criteria: "Urgent if: stock < 10% of safety stock. Reorder soon if: stock < 30% of safety stock or trending down fast. Monitor if: adequate for 2+ weeks. Flag overstock if: >200% of target.",
            model: "sonnet",
          },
          dependsOn: ["fetch_inventory"],
        },
        {
          id: "generate_reorder_list",
          name: "Generate Reorder Recommendations",
          type: "ai_generate",
          config: {
            instructions: "Create a reorder recommendation list. For each item: SKU, current stock, reorder quantity (based on avg consumption rate × lead time × 1.2 safety factor), preferred supplier, estimated cost. Return as JSON array.",
            context: { inventory: "{{fetch_inventory}}", analysis: "{{analyze_inventory}}" },
            model: "sonnet",
          },
          dependsOn: ["analyze_inventory"],
        },
        {
          id: "approval_reorder",
          name: "Approve Reorder",
          type: "approval",
          config: {
            title: "Inventory Reorder Approval",
            description: "{{generate_reorder_list.rawText}}",
            channels: ["slack", "dashboard"],
            priority: "high",
            expiresInMinutes: 480,
          },
          dependsOn: ["generate_reorder_list"],
        },
        {
          id: "notify_ops_inventory",
          name: "Alert Ops Team",
          type: "action",
          config: { action: "send_slack", channel: "#ops", message: "📦 Daily Inventory Alert:\n{{analyze_inventory.reasoning}}" },
          dependsOn: ["analyze_inventory"],
        },
      ],
      edges: [
        { from: "fetch_inventory", to: "analyze_inventory" },
        { from: "analyze_inventory", to: "generate_reorder_list" },
        { from: "analyze_inventory", to: "notify_ops_inventory" },
        { from: "generate_reorder_list", to: "approval_reorder" },
      ],
    },

    // ── 4. SLA Monitoring ───────────────────────────────
    {
      id: "ops-sla-monitoring",
      name: "SLA Monitoring",
      description: "Tracks SLA compliance across vendors and services, generates reports, flags breaches",
      triggerEvent: "sla.check",
      triggerSchedule: "0 9 * * 1-5",
      tags: ["sla", "monitoring", "compliance"],
      estimatedCostCents: 3,
      nodes: [
        {
          id: "fetch_sla_data",
          name: "Fetch SLA Metrics",
          type: "fetch",
          config: { provider: "internal", operation: "sla.metrics", params: { period: "last_24h" } },
        },
        {
          id: "analyze_sla",
          name: "AI Analyze SLA Compliance",
          type: "ai_classify",
          config: {
            text: "{{fetch_sla_data}}",
            categories: ["all_compliant", "minor_breaches", "major_breaches", "critical_breaches"],
            context: { thresholds: "Uptime: 99.9%, Response time: <500ms p95, Error rate: <0.1%" },
            model: "haiku",
          },
          dependsOn: ["fetch_sla_data"],
        },
        {
          id: "generate_sla_report",
          name: "Generate SLA Report",
          type: "ai_generate",
          config: {
            instructions: "Generate a concise SLA compliance report. Include: overall status, services in breach, trend vs last period, recommended actions. Format for Slack (use emoji, keep under 300 words).",
            context: { metrics: "{{fetch_sla_data}}", analysis: "{{analyze_sla}}" },
            model: "haiku",
          },
          dependsOn: ["analyze_sla"],
        },
        {
          id: "route_sla",
          name: "Route by Compliance",
          type: "condition",
          config: { category: "{{analyze_sla.category}}" },
          dependsOn: ["analyze_sla"],
        },
        {
          id: "send_report",
          name: "Send Daily Report",
          type: "action",
          config: { action: "send_slack", channel: "#ops", message: "📊 Daily SLA Report:\n{{generate_sla_report.rawText}}" },
          dependsOn: ["generate_sla_report"],
        },
        {
          id: "escalate_breach",
          name: "Escalate SLA Breach",
          type: "action",
          config: { action: "send_slack", channel: "#ops-urgent", message: "🔴 CRITICAL SLA BREACH detected!\n{{generate_sla_report.rawText}}" },
          dependsOn: ["route_sla"],
        },
      ],
      edges: [
        { from: "fetch_sla_data", to: "analyze_sla" },
        { from: "analyze_sla", to: "generate_sla_report" },
        { from: "analyze_sla", to: "route_sla" },
        { from: "generate_sla_report", to: "send_report" },
        { from: "route_sla", to: "escalate_breach", condition: { field: "category", operator: "eq", value: "critical_breaches" } },
        { from: "route_sla", to: "escalate_breach", condition: { field: "category", operator: "eq", value: "major_breaches" } },
      ],
    },
  ],
};
