// ═══════════════════════════════════════════════════════
// SALES PACK — Lead routing, pipeline management,
// proposal generation, deal alerts
// ═══════════════════════════════════════════════════════

import type { WorkflowPack } from "./index";

export const salesPack: WorkflowPack = {
  id: "sales",
  name: "Sales Pack",
  description: "Automate lead routing, pipeline management, proposal generation, and deal intelligence",
  icon: "🎯",
  color: "#8B5CF6",
  requiredIntegrations: ["slack", "gmail", "hubspot"],
  workflows: [
    // ── 1. Lead Routing ─────────────────────────────────
    {
      id: "sales-lead-routing",
      name: "Lead Routing",
      description: "Scores inbound leads, enriches with company data, routes to the right rep based on territory, size, and expertise",
      triggerEvent: "lead.created",
      tags: ["leads", "routing", "scoring"],
      estimatedCostCents: 4,
      nodes: [
        {
          id: "enrich_lead",
          name: "Enrich Lead Data",
          type: "fetch",
          config: { provider: "hubspot", operation: "contacts.get", params: { email: "{{trigger.payload.email}}" } },
        },
        {
          id: "score_lead",
          name: "AI Score Lead",
          type: "ai_decide",
          config: {
            question: "Score this lead from 1-100 and classify its priority",
            options: ["hot_lead", "warm_lead", "nurture", "disqualified"],
            context: {
              name: "{{trigger.payload.name}}",
              email: "{{trigger.payload.email}}",
              company: "{{trigger.payload.company}}",
              source: "{{trigger.payload.source}}",
              enrichedData: "{{enrich_lead}}",
              message: "{{trigger.payload.message}}",
            },
            criteria: "Hot if: enterprise company, explicit buying intent, budget mentioned. Warm if: mid-market, exploring solutions. Nurture if: early stage, educational content interest. Disqualify if: competitor, student, spam.",
            model: "sonnet",
          },
          dependsOn: ["enrich_lead"],
        },
        {
          id: "route_lead",
          name: "Route by Score",
          type: "condition",
          config: { decision: "{{score_lead.decision}}" },
          dependsOn: ["score_lead"],
        },
        {
          id: "assign_hot",
          name: "Assign Hot Lead",
          type: "action",
          config: {
            action: "update_crm",
            provider: "hubspot",
            objectType: "contact",
            properties: { email: "{{trigger.payload.email}}", lifecyclestage: "salesqualifiedlead", lead_status: "NEW", hs_lead_status: "NEW" },
          },
          dependsOn: ["route_lead"],
        },
        {
          id: "notify_rep_hot",
          name: "Alert Sales Rep (Hot)",
          type: "action",
          config: { action: "send_slack", channel: "#sales-hot", message: "🔥 Hot lead! {{trigger.payload.name}} from {{trigger.payload.company}}\nScore: {{score_lead.scores}}\nSource: {{trigger.payload.source}}\n\n{{score_lead.reasoning}}" },
          dependsOn: ["assign_hot"],
        },
        {
          id: "add_to_nurture",
          name: "Add to Nurture Sequence",
          type: "action",
          config: {
            action: "update_crm",
            provider: "hubspot",
            objectType: "contact",
            properties: { email: "{{trigger.payload.email}}", lifecyclestage: "lead", lead_status: "NURTURE" },
          },
          dependsOn: ["route_lead"],
        },
        {
          id: "send_welcome",
          name: "Send Welcome Email",
          type: "ai_generate",
          config: {
            instructions: "Write a personalized welcome email based on their source and interest. If from content download, reference the content. If from demo request, confirm and set expectations. Be warm, brief (under 100 words), include a clear next step.",
            context: { name: "{{trigger.payload.name}}", company: "{{trigger.payload.company}}", source: "{{trigger.payload.source}}", score: "{{score_lead.decision}}" },
            model: "haiku",
          },
          dependsOn: ["score_lead"],
        },
        {
          id: "send_welcome_email",
          name: "Send Welcome Email",
          type: "action",
          config: { action: "send_email", to: "{{trigger.payload.email}}", subject: "Welcome, {{trigger.payload.name}}!", body: "{{send_welcome.rawText}}" },
          dependsOn: ["send_welcome"],
        },
        {
          id: "log_lead",
          name: "Log to Sales Channel",
          type: "action",
          config: { action: "send_slack", channel: "#sales", message: "New lead: {{trigger.payload.name}} ({{trigger.payload.company}}) — {{score_lead.decision}}" },
          dependsOn: ["score_lead"],
        },
      ],
      edges: [
        { from: "enrich_lead", to: "score_lead" },
        { from: "score_lead", to: "route_lead" },
        { from: "score_lead", to: "send_welcome" },
        { from: "score_lead", to: "log_lead" },
        { from: "route_lead", to: "assign_hot", condition: { field: "decision", operator: "eq", value: "hot_lead" } },
        { from: "route_lead", to: "assign_hot", condition: { field: "decision", operator: "eq", value: "warm_lead" } },
        { from: "route_lead", to: "add_to_nurture", condition: { field: "decision", operator: "eq", value: "nurture" } },
        { from: "assign_hot", to: "notify_rep_hot" },
        { from: "send_welcome", to: "send_welcome_email" },
      ],
    },

    // ── 2. Pipeline Management ──────────────────────────
    {
      id: "sales-pipeline",
      name: "Pipeline Health Check",
      description: "Daily analysis of deal pipeline: stale deals, at-risk opportunities, coaching recommendations",
      triggerEvent: "pipeline.check",
      triggerSchedule: "0 8 * * 1-5",
      tags: ["pipeline", "deals", "forecasting"],
      estimatedCostCents: 5,
      nodes: [
        {
          id: "fetch_pipeline",
          name: "Fetch Active Deals",
          type: "fetch",
          config: { provider: "hubspot", operation: "deals.list", params: { stage: "active", properties: "dealname,amount,dealstage,closedate,hubspot_owner_id,notes_last_updated" } },
        },
        {
          id: "analyze_pipeline",
          name: "AI Pipeline Analysis",
          type: "ai_generate",
          config: {
            instructions: "Analyze this sales pipeline and identify: (1) Stale deals — no activity in 14+ days, (2) At-risk deals — close date passed or approaching with no recent engagement, (3) Top opportunities — highest value deals likely to close this month, (4) Coaching recommendations — patterns in lost/stale deals. Return JSON with: staleDealIds, atRiskDealIds, topOpportunities, coachingInsights, totalPipelineValue, forecastedCloseThisMonth.",
            context: { deals: "{{fetch_pipeline}}" },
            model: "sonnet",
          },
          dependsOn: ["fetch_pipeline"],
        },
        {
          id: "generate_report",
          name: "Generate Pipeline Report",
          type: "ai_summarize",
          config: {
            text: "{{analyze_pipeline.rawText}}",
            style: "executive",
            maxLength: 300,
            model: "haiku",
          },
          dependsOn: ["analyze_pipeline"],
        },
        {
          id: "send_pipeline_report",
          name: "Send Pipeline Report",
          type: "action",
          config: { action: "send_slack", channel: "#sales", message: "📊 Daily Pipeline Report:\n{{generate_report.summary}}" },
          dependsOn: ["generate_report"],
        },
        {
          id: "alert_stale",
          name: "Alert on Stale Deals",
          type: "action",
          config: { action: "send_slack", channel: "#sales", message: "⚠️ Stale deals detected (no activity 14+ days):\n{{analyze_pipeline.output.staleDealIds}}\n\nPlease update or close these opportunities." },
          dependsOn: ["analyze_pipeline"],
        },
      ],
      edges: [
        { from: "fetch_pipeline", to: "analyze_pipeline" },
        { from: "analyze_pipeline", to: "generate_report" },
        { from: "analyze_pipeline", to: "alert_stale" },
        { from: "generate_report", to: "send_pipeline_report" },
      ],
    },

    // ── 3. Proposal Generation ──────────────────────────
    {
      id: "sales-proposal",
      name: "Proposal Generation",
      description: "Generates customized proposals from deal data, routes for approval, sends to prospect",
      triggerEvent: "proposal.requested",
      tags: ["proposal", "deals", "documents"],
      estimatedCostCents: 8,
      nodes: [
        {
          id: "fetch_deal",
          name: "Fetch Deal Details",
          type: "fetch",
          config: { provider: "hubspot", operation: "deals.get", params: { dealId: "{{trigger.payload.dealId}}", associations: "contacts,companies" } },
        },
        {
          id: "generate_proposal",
          name: "AI Generate Proposal",
          type: "ai_generate",
          config: {
            instructions: "Generate a professional business proposal. Include: executive summary (why they need this), proposed solution (tailored to their needs), pricing breakdown, timeline, terms. Match the tone to their company size — enterprise=formal, startup=casual. Return structured JSON with sections.",
            context: {
              deal: "{{fetch_deal}}",
              companyName: "{{trigger.payload.companyName}}",
              contactName: "{{trigger.payload.contactName}}",
              requirements: "{{trigger.payload.requirements}}",
              pricingTier: "{{trigger.payload.pricingTier}}",
            },
            model: "sonnet",
          },
          dependsOn: ["fetch_deal"],
        },
        {
          id: "review_proposal",
          name: "Manager Reviews Proposal",
          type: "approval",
          config: {
            title: "Proposal Review: {{trigger.payload.companyName}} — {{trigger.payload.dealValue}}",
            description: "Proposal for {{trigger.payload.contactName}} at {{trigger.payload.companyName}}.\n\nDeal value: {{trigger.payload.dealValue}}\nTier: {{trigger.payload.pricingTier}}\n\n{{generate_proposal.rawText}}",
            channels: ["slack", "dashboard"],
            priority: "high",
            expiresInMinutes: 1440,
          },
          dependsOn: ["generate_proposal"],
        },
        {
          id: "send_proposal",
          name: "Send Proposal Email",
          type: "ai_generate",
          config: {
            instructions: "Write a brief, professional email to accompany the proposal. Reference their specific needs, express enthusiasm about working together, and provide a clear CTA to schedule a call to discuss. Under 100 words.",
            context: { contactName: "{{trigger.payload.contactName}}", companyName: "{{trigger.payload.companyName}}", proposal: "{{generate_proposal.output}}" },
            model: "haiku",
          },
          dependsOn: ["review_proposal"],
        },
        {
          id: "send_proposal_email",
          name: "Email Proposal",
          type: "action",
          config: { action: "send_email", to: "{{trigger.payload.contactEmail}}", subject: "Proposal for {{trigger.payload.companyName}}", body: "{{send_proposal.rawText}}" },
          dependsOn: ["send_proposal"],
        },
        {
          id: "update_deal_stage",
          name: "Update Deal Stage",
          type: "action",
          config: { action: "update_crm", provider: "hubspot", objectType: "deal", properties: { dealId: "{{trigger.payload.dealId}}", dealstage: "proposalSent" } },
          dependsOn: ["send_proposal_email"],
        },
        {
          id: "notify_team",
          name: "Notify Sales Team",
          type: "action",
          config: { action: "send_slack", channel: "#sales", message: "📤 Proposal sent to {{trigger.payload.contactName}} at {{trigger.payload.companyName}} ({{trigger.payload.dealValue}})" },
          dependsOn: ["send_proposal_email"],
        },
      ],
      edges: [
        { from: "fetch_deal", to: "generate_proposal" },
        { from: "generate_proposal", to: "review_proposal" },
        { from: "review_proposal", to: "send_proposal" },
        { from: "send_proposal", to: "send_proposal_email" },
        { from: "send_proposal_email", to: "update_deal_stage" },
        { from: "send_proposal_email", to: "notify_team" },
      ],
    },

    // ── 4. Deal Alerts ──────────────────────────────────
    {
      id: "sales-deal-alerts",
      name: "Deal Stage Alerts",
      description: "Monitors deal stage changes, generates coaching tips, celebrates wins",
      triggerEvent: "deal.updated",
      tags: ["deals", "alerts", "coaching"],
      estimatedCostCents: 2,
      nodes: [
        {
          id: "classify_change",
          name: "Classify Deal Change",
          type: "ai_classify",
          config: {
            text: "Deal {{trigger.payload.dealName}} moved from {{trigger.payload.previousStage}} to {{trigger.payload.newStage}}. Value: {{trigger.payload.amount}}",
            categories: ["deal_won", "deal_lost", "moved_forward", "moved_backward", "stalled"],
            context: { dealName: "{{trigger.payload.dealName}}", owner: "{{trigger.payload.ownerName}}" },
            model: "haiku",
          },
        },
        {
          id: "route_change",
          name: "Route by Change Type",
          type: "condition",
          config: { category: "{{classify_change.category}}" },
          dependsOn: ["classify_change"],
        },
        {
          id: "celebrate_win",
          name: "Celebrate Win",
          type: "action",
          config: { action: "send_slack", channel: "#wins", message: "🎉🎉🎉 DEAL WON! {{trigger.payload.dealName}} — {{trigger.payload.amount}}\nClosed by {{trigger.payload.ownerName}}! 🏆" },
          dependsOn: ["route_change"],
        },
        {
          id: "analyze_loss",
          name: "Analyze Deal Loss",
          type: "ai_generate",
          config: {
            instructions: "Analyze why this deal was lost based on the available context. Suggest 2-3 things to try differently next time. Be constructive, not blaming. Under 100 words.",
            context: { dealName: "{{trigger.payload.dealName}}", previousStage: "{{trigger.payload.previousStage}}", lossReason: "{{trigger.payload.lossReason}}", owner: "{{trigger.payload.ownerName}}" },
            model: "haiku",
          },
          dependsOn: ["route_change"],
        },
        {
          id: "notify_loss",
          name: "Notify on Loss",
          type: "action",
          config: { action: "send_slack", channel: "#sales", message: "📉 Deal lost: {{trigger.payload.dealName}} ({{trigger.payload.amount}})\n\nLearnings: {{analyze_loss.rawText}}" },
          dependsOn: ["analyze_loss"],
        },
        {
          id: "coaching_tip",
          name: "Generate Coaching Tip",
          type: "ai_generate",
          config: {
            instructions: "Based on this deal moving backward, generate a brief coaching tip for the rep. Reference a specific sales methodology or best practice. Under 50 words.",
            context: { dealName: "{{trigger.payload.dealName}}", from: "{{trigger.payload.previousStage}}", to: "{{trigger.payload.newStage}}" },
            model: "haiku",
          },
          dependsOn: ["route_change"],
        },
        {
          id: "send_coaching",
          name: "Send Coaching DM",
          type: "action",
          config: { action: "send_slack", channel: "{{trigger.payload.ownerSlack}}", message: "💡 Quick coaching tip for {{trigger.payload.dealName}}:\n{{coaching_tip.rawText}}" },
          dependsOn: ["coaching_tip"],
        },
      ],
      edges: [
        { from: "classify_change", to: "route_change" },
        { from: "route_change", to: "celebrate_win", condition: { field: "category", operator: "eq", value: "deal_won" } },
        { from: "route_change", to: "analyze_loss", condition: { field: "category", operator: "eq", value: "deal_lost" } },
        { from: "route_change", to: "coaching_tip", condition: { field: "category", operator: "eq", value: "moved_backward" } },
        { from: "analyze_loss", to: "notify_loss" },
        { from: "coaching_tip", to: "send_coaching" },
      ],
    },
  ],
};
